
[tool.pytest.ini_options] 
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s | %(filename)s:%(lineno)d:%(function)s | %(levelname)s | %(message)s"

[tool.poetry]
name = "compare-my-stocks"
version = "0.1.0"
description = ""
authors = ["eyalk5"]
readme = "README.md"
packages = [{include = "compare_my_stocks"}]

[tool.poetry.dependencies]
python = "^3.9"
flask = ">=2.0.1,<2.1.0"
numpy = ">=1.22.0,<1.23.0"
requests = ">=2.26.0,<2.27.0"
pyside6 = ">=6.2.0,<6.3.0"
matplotlib = ">=3.5.0rc1,<3.6.0"
pandas = ">=1.3.2,<1.4.0"
python-dateutil = ">=2.8.2,<2.9.0"
pytz = ">=2021.3,<2022.0"
json-editor = {git = "https://github.com/eyalk11/json-editor.git"}
investpy = {git = "https://github.com/eyalk11/investpy.git"}
qtvoila = {git = "https://github.com/eyalk11/qtvoila.git"}
superqt = ">=0.2.5.post1,<0.3.0"
mplcursors = ">=0.4,<1.0"
django = ">=3.2.9,<3.3.0"
nbmanager = {git = "https://github.com/jupyter/nbmanager.git"}
ib-insync = "^0.9.85"
pyro5 = ">=5.14,<6.0"
ibflex = ">=0.15,<1.0"
colorlog = ">=6.7.0,<6.8.0"
qt-collapsible-section = {git = "https://github.com/eyalk11/qt-collapsible-section.git"}
six = ">=1.16.0,<1.17.0"
psutil = ">=5.8.0,<5.9.0"
dacite = ">=1.8.0,<1.9.0"
dataconf = ">=2.1.3,<2.2.0"
toml = ">=0.10.2,<0.11.0"
pytest = ">=7.2.0,<7.3.0"
ipykernel = ">=6.0.3,<6.1.0"
setuptools = ">=60.2.0,<60.3.0"
nbformat = ">=5.7.3,<5.8.0"
"ruamel.yaml" = "^0.17.31"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
