
[tool.pytest.ini_options] 
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s | %(filename)s:%(lineno)d:%(function)s | %(levelname)s | %(message)s"

[tool.poetry]
name = "compare-my-stocks"
version = "0.1.0"
description = ""
authors = ["eyalk5"]
readme = "README.md"
packages = [{include = "compare_my_stocks", from = "src"}]
include = [  "src/compare_my_stocks/data",
"src/compare_my_stocks/gui/mainwindow.ui",
"src/compare_my_stocks/common/impacketLICENSE"]


[tool.poetry.dependencies]
colorlog = ">=6.7.0,<6.8.0"
django = ">=3.2.9,<3.3.0"
numpy = ">=1.22.0,<1.23.0"
"ruamel.yaml" = "^0.17.31"

dacite = ">=1.8.0,<1.9.0"
python = "^3.9"

flask = {version=">=2.0.1,<2.1.0", optional= true}
requests = {version=">=2.26.0,<2.27.0", optional= true}
pyside6 = {version=">=6.2.0,<6.3.0", optional= true}
matplotlib = {version=">=3.5.0rc1,<3.6.0", optional= true}
pandas = {version=">=1.3.2,<1.4.0", optional= true}
python-dateutil = {version=">=2.8.2,<2.9.0", optional= true}
pytz = {version=">=2021.3,<2022.0", optional= true}
json-editor = {git = "https://github.com/eyalk11/json-editor.git", optional= true}
investpy = {git = "https://github.com/eyalk11/investpy.git", optional= true}
qtvoila = {git = "https://github.com/eyalk11/qtvoila.git", optional= true}
superqt = {version=">=0.2.5.post1,<0.3.0", optional= true}
mplcursors = {version=">=0.4,<1.0", optional= true}
nbmanager = {git = "https://github.com/jupyter/nbmanager.git", optional= true}
ib-insync = {version="^0.9.85", optional= true}
pyro5 = {version=">=5.14,<6.0", optional= true}
ibflex = {version=">=0.15,<1.0", optional= true}
qt-collapsible-section = {git = "https://github.com/eyalk11/qt-collapsible-section.git", optional= true}
six = {version=">=1.16.0,<1.17.0", optional= true}
psutil = {version=">=5.8.0,<5.9.0", optional= true}
dataconf = {version=">=2.1.3,<2.2.0", optional= true}
toml = {version=">=0.10.2,<0.11.0", optional= true}
pytest = {version=">=7.2.0,<7.3.0", optional= true}
ipykernel = {version="*", optional= true}
setuptools = {version=">=60.2.0,<60.3.0", optional= true}
nbformat = {version=">=5.7.3,<5.8.0", optional= true}
voila = {version="*", optional= true}

[tool.poetry.extras]
full = [ 'flask','requests','pyside6','matplotlib','pandas','python','pytz','json-editor','investpy','qtvoila','superqt','mplcursors','nbmanager','ib-insync','pyro5','ibflex','qt-collapsible-section','six','psutil','dataconf','toml','pytest','ipykernel','setuptools','nbformat', 'colorlog','django','numpy','ruamel.yaml']
mini = ['colorlog','django','numpy','ruamel.yaml']
jupyter = ['colorlog','django','numpy','ruamel.yaml','voila','ipykernel']

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
