[general]
HOSTIB = "127.0.0.1"
PORTIB = 7596
IBSRVPORT = 9091
ADDPROCESS = ["ibsrv.exe"]
LOADLASTATBEGIN = true
LASTGRAPHNAME = "Last"
IGNORE_ADJUST = 1
SKIP_EARNINGS = 1
TRYSTORAGEFOREARNINGS = 1
DATAFILEPTR = "DATA_FILE"
USEWX = 0
USEWEB = 0
USEQT = 1
SIMPLEMODE = 0
DEFAULTCURR = ["USD", "EUR", "GBP", "ILS"]
MAXCACHETIMESPAN = "1 day"
HIST_F = "hist_file.cache"
HIST_F_BACKUP = "hist_file.cache.back"
DEFAULTNOTEBOOK = "jupyter\\defaultnotebook.ipynb"
PORT = 4001
EXT = ["QQQ"]
DEF_FIG_SIZE = [6.6, 3.0]
EXCHANGES = ["nyse", "nasdaq", "xetra", "nyse", "london", "otc markets"]
VALIDEXCHANGES = ["NYSE", "NASDAQ", "ISLAND", "XERTA", "LSE"]
TRANSLATE_EXCHANGES = { "NASDAQ" = "NYSE" }
DEFAULTFROMDATE = "2020-01-01T00:00:00Z"
EXCHANGE_CURRENCY = { "London" = "GBP", "Xetra" = "EUR" }
STOCK_CURRENCY = { "VETH.DE" = "EUR", "VBTC1" = "EUR" }
MINCOLFORCOLUMS = 20
MIN = 4000
MAXCOLS = 30
MINCHECKREQ = 10
MINIMALPRECREQ = 0.2
CACHEUSAGE = "FORCEUSE"
DOWNLOADDATAFORPROT = true
JSONFILENAME = "groups.json"
SERIALIZEDFILE = "serialized.dat"
EARNINGSTORAGE = "earnings.dat"
TRANSLATEDIC = { "VETHG.DE" = "VETH", "VTBC.DE" = "VBTC1", "ADA-USD" = "cardano", "VUKE.L" = "VUKE" }
CRYPTO = ["cardano", "bitcoin", "ethereum"]
GRAPHFN = "graphs.json"
BASECUR = "USD"
REVENUEFILE = "NOEARNINGS"
INCOMEFILE = "NOEARNINGS"
COMMONSTOCK = "NOEARNINGS"
IGNORED_SYMBOLS = ["FB"]
StockPricesHeaders = { "X-RapidAPI-Host" = "stock-prices2.p.rapidapi.com", "X-RapidAPI-Key" = null }
SEEKINGALPHAHeaders = { "X-RapidAPI-Host" = "seeking-alpha.p.rapidapi.com", "X-RapidAPI-Key" = null }

[export]
EXPORTEDPORT = "exported.csv"
BOTHSYMBOLS = []
MAXPERCDIFFIBSTOCKWARN = 0.2
FIXBUYSELLDIFFDAYS = 3
NORMALIZE_ON_TRANSACTIONSAVE = 0
DONT_RUN_NOTEBOOK = false
STOP_EXCEPTION_IN_DEBUG = true
VERIFY_SAVING = "Ask"
CHECKRELOADINTERVAL = 30
COMBINESTRATEGY = "PREFERSTOCKS"
IGNORECONF = {}
LOGFILE = "log.txt"
LOGERRORFILE = "error.log"
VOILA_PYTHON_PROCESS_PATH = null
AUTO_RESOVLE_VOILA_PYTHON = true
